openapi: 3.0.0
info:
  description: Stuff Lightning Talk API
  version: 1.0.0
  title: Stuff Lightning Talk API
  contact:
    email: miztaka@honestyworks.jp
paths:
  /talks:
    post:
      summary: Submit a new talk
      operationId: createTalk
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TalkSubmission"
      responses:
        "200":
          description: "Accepted"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Talk"
        "400":
          description: "Invalid values"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
    get:
      summary: Get all talks for next session.
      operationId: findTalks
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Talk"
servers:
  - url: http://localhost:8080/api/v1
components:
  schemas:
    TalkSubmission:
      type: object
      properties:
        topic:
          type: string
          maxLength: 80
        description:
          type: string
          description: 120 words maximum
        email:
          type: string
          format: email
          maxLength: 255
      required:
      - topic
      - description
      - email
    Talk:
      allOf:
        - $ref: "#/components/schemas/TalkSubmission"
        - type: object
          properties:
            id:
              type: integer
              format: int64
            submittedAt:
              type: string
              format: date-time
            sessionDate:
              type: string
              format: date
            ipaddr:
              type: string
            hostname:
              type: string
            os:
              type: string
            browser:
              type: string
    ApiError:
      type: object
      properties:
        msg:
          type: string

