version: '3.1'

services:
  db:
    image: mysql:5.7
    ports:
      - "13306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: lightning_talk
      MYSQL_USER: lightning_talk
      MYSQL_PASSWORD: lightning_talk
      TZ: Pacific/Auckland

